/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import scala.collection.immutable.Set

case class Product(
  id: Option[Long] = None,
  name: Option[String] = None,
  features: Option[Set[Feature]] = None,
  constraints: Option[Set[FeatureConstraint]] = None
)

